version: '1'

services:
  mlflow:
    build: mlflow
    environment:
      - MLFLOW_PORT=5555
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_ARTIFACT_ROOT=s3://mlflow-artifacts
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "5555:5555"
    depends_on:
      - minio
      - postgres
    command: mlflow server --backend-store-uri postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB --default-artifact-root s3://mlflow_bucket/mlflow/ --host 0.0.0.0
  minio:
    image: minio/minio:RELEASE.2023-01-20T02-05-44Z.hotfix.4d6508537
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./minio-data:/data
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    tty: true # needed to run app in dev mode should be replaced
    stdin_open: true # needed to run app in dev mode should be replaced
    build: app
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5555
    depends_on:
      - mlflow
    networks:
      - mlflow_network
    volumes:
      - ./app:/app


volumes:
  mlflow:
  postgres:
  minio:

networks:
  mlflow_network: